spring:
  datasource:
    url: jdbc:mysql://localhost:3306/prodavalnik-suppliers
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
